# Generated by Django 5.1.6 on 2025-03-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicing_image_vehicle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
    ]
