# Generated by Django 5.1.6 on 2025-04-12 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_vehicle_discount_vehiclebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.vehicle', verbose_name='Associated Vehicle'),
        ),
    ]
