# Generated by Django 5.1.6 on 2025-04-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_booking_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicing',
            name='city',
            field=models.CharField(blank=True, help_text='City where the service is available', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='city',
            field=models.CharField(blank=True, help_text='City where the vehicle is available', max_length=100, null=True),
        ),
    ]
