# Generated by Django 5.1.6 on 2025-04-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
